### ISSUE TITLE
Bug in Method BuildImportTable()

### ISSUE THREAD

**Issue by khalthag** [Scavanger/MemoryModule.net#1]
Hi,

i think there is a bug near line 305 in MemoryModule.cs.

if (NativeDeclarations.IMAGE_SNAP_BY_ORDINAL32(_thunkRef))
{
    procName = Marshal.PtrToStringAnsi(new IntPtr(NativeDeclarations.IMAGE_ORDINAL32(_thunkRef)));
    *funcRef = (int)NativeDeclarations.GetProcAddress(handle, procName);
}

The function GetProcAddress() accepts an ordinal value encoded as LPCSTR. Thus pointer points at no valid location, so i think there is no way to submit it as a string. But you can use a different signature for GetProcAddress():
public static extern UIntPtr GetProcAddress(IntPtr hModule, IntPtr procName);

and then call _funcRef = (int)NativeDeclarations.GetProcAddress(handle, new IntPtr(NativeDeclarations.IMAGE_ORDINAL32(_thunkRef))).

**Comment by Scavanger** [comment]
This works, because Strings are automatic converted to Pointer (LPCSTR) by the CLI and vice versa when a native function is called.
 
After a long time i worked again on this code and it is bullshit to convert a pointer to string and the CLI converts the string back to a pointer one line later . So you way is better.
